@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;

if () then ([command modifies address book])
  :Call Model#saveState();
  :Save current state to undoStack;
  :Clear redoStack;
  :Execute command;
else ([else])
  :Execute command;
endif

:Return result to user;

stop
@enduml
