@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant "undoStack:Stack<State>" as UndoStack MODEL_COLOR
participant "redoStack:Stack<State>" as RedoStack MODEL_COLOR
participant "currentState:State" as CurrentState MODEL_COLOR
end box

[-> ModelManager : undo()
activate ModelManager

create CurrentState
ModelManager -> CurrentState : new State(addressBook)
activate CurrentState

CurrentState --> ModelManager
deactivate CurrentState

ModelManager -> RedoStack : push(currentState)
activate RedoStack

RedoStack --> ModelManager
deactivate RedoStack

ModelManager -> UndoStack : pop()
activate UndoStack

UndoStack --> ModelManager : previousState
deactivate UndoStack

ModelManager -> AddressBook : resetData(previousState.getAddressBook())
activate AddressBook

AddressBook --> ModelManager
deactivate AddressBook

[<-- ModelManager
deactivate ModelManager
@enduml
